enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app

# commented to use nproc instead
# parallel-jobs = 4

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# I only build arm64-v8a apks

# [YouTube-anddea]
# app-name = "YouTube"
# rv-brand = "anddea"
# arch = "arm64-v8a"
# patches-source = "anddea/revanced-patches"
# integrations-source = "anddea/revanced-integrations"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [Music-anddea]
# app-name = "YT Music"
# rv-brand = "anddea"
# version = "8.25.54"
# arch = "arm64-v8a"
# patches-source = "anddea/revanced-patches"
# integrations-source = "anddea/revanced-integrations"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
# excluded-patches = "'Translations for YouTube Music'"

[YouTube-Morphe]
app-name = "YouTube"
rv-brand = "Morphe"
arch = "arm64-v8a"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
patches-source = "MorpheApp/morphe-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

# [YTMusic-Morphe]
# app-name = "YT Music"
# rv-brand = "Morphe"
# arch = "arm64-v8a"
# cli-source = "MorpheApp/morphe-cli"
# cli-version = "dev"
# patches-source = "MorpheApp/morphe-patches"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

# [Spotify]
# app-name = "Spotify"
# # arch = "arm64-v8a"
# rv-brand = "anddea"
# patches-source = "anddea/revanced-patches"
# integrations-source = "anddea/revanced-integrations"
# uptodown-dlurl = "https://spotify.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

# [Reddit-anddea]
# app-name = "Reddit"
# version = "2025.12.1"
# apkmirror-dpi = "120-640dpi"
# # arch = "arm64-v8a"
# rv-brand = "anddea"
# patches-source = "anddea/revanced-patches"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
# uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Reddit-morphe]
app-name = "Reddit"
# version = "2025.12.1"
apkmirror-dpi = "nodpi anydpi 120-640dpi"
arch = "arm64-v8a"
rv-brand = "Morphe"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
patches-source = "MorpheApp/morphe-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[GooglePhotos]
app-name = "GPhotos"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

# [Messenger]
# arch = "arm64-v8a"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
# uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
# excluded-patches = "'Remove Meta AI'"

# [Facebook]
# arch = "arm64-v8a"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
# uptodown-dlurl = "https://facebook.en.uptodown.com/android"

# [Lightroom]
# # apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
# arch = "arm64-v8a"
# uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"

# [Strava]
# # apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/"
# arch = "arm64-v8a"
# uptodown-dlurl = "https://strava.en.uptodown.com/android/download"
